services:
  app:
    build: ./docker
    ports:
      - 8080:80
  db:
    image: mysql:8.2
    volumes:
      - ./db-data/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Gg62zWrT
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=nNi3RqmY
